core/urls.py
from . import views
from django.urls import path


app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),

    path('settings/', views.Settings.as_view(), name='setting_list'),
    path("academic-year/<str:pk>/", views.SettingsDetailView.as_view(), name="setting_detail"),
    path('settings-create/', views.SettingsCreate.as_view(), name='setting_create'),
    path("academic-year/<str:pk>/update/", views.SettingsUpdateView.as_view(), name="setting_update"),
    path("academic-year/<str:pk>/delete/", views.SettingsDeleteView.as_view(), name="setting_delete"),

    #ID Card
    path("id-card/<str:pk>/", views.IDCardView.as_view(), name="id_card"),
    path("id-card/", views.IDCardView.as_view(), name="my_id_card"),
    
]

employees/urls.py
from . import views
from django.urls import path


app_name = "employees"

urlpatterns = [
    path("department/", views.DepartmentListView.as_view(), name="department_list"),
    path("department/<str:pk>/", views.DepartmentDetailView.as_view(), name="department_detail"),
    path("new/department/", views.DepartmentCreateView.as_view(), name="department_create"),
    path("department/<str:pk>/update/", views.DepartmentUpdateView.as_view(), name="department_update"),
    path("department/<str:pk>/delete/", views.DepartmentDeleteView.as_view(), name="department_delete"),
    #
    path("designation/", views.DesignationListView.as_view(), name="designation_list"),
    path("designation/<str:pk>/", views.DesignationDetailView.as_view(), name="designation_detail"),
    path("new/designation/", views.DesignationCreateView.as_view(), name="designation_create"),
    path("designation/<str:pk>/update/", views.DesignationUpdateView.as_view(), name="designation_update"),
    path("designation/<str:pk>/delete/", views.DesignationDeleteView.as_view(), name="designation_delete"),
    #
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("employees/", views.EmployeeListView.as_view(), name="employee_list"),
    path("tele-callers/", views.TeleCallerListView.as_view(), name="tele_caller_list"),
    
    path("employees/add/", views.EmployeeCreateView.as_view(), name="employee_create"),
    path("view/<pk>/", views.EmployeeDetailView.as_view(), name="employee_detail"),
    path("employees/change/<pk>/", views.EmployeeUpdateView.as_view(), name="employee_update"),
    path("employees/delete/<pk>/", views.EmployeeDeleteView.as_view(), name="employee_delete"),
]

masters/urls.py
from . import views
from django.urls import path


app_name = "masters"

urlpatterns = [
    path('update_status/<int:pk>/', views.status_update, name='status_update'),

    # Batch
    path("batch/list/", views.BatchListView.as_view(), name="batch_list"),
    path("batch/<str:pk>/detail/", views.BatchDetailView.as_view(), name="batch_detail"),
    path("batch/create/", views.BatchCreateView.as_view(), name="batch_create"),
    path("batch/<str:pk>/update/", views.BatchUpdateView.as_view(), name="batch_update"),
    path("batch/<str:pk>/delete/", views.BatchDeleteView.as_view(), name="batch_delete"),
    
    # Course
    path("course/list/", views.CourseListView.as_view(), name="course_list"),
    path("course/<str:pk>/detail/", views.CourseDetailView.as_view(), name="course_detail"),
    path("course/create/", views.CourseCreateView.as_view(), name="course_create"),
    path("course/<str:pk>/update/", views.CourseUpdateView.as_view(), name="course_update"),
    path("course/<str:pk>/delete/", views.CourseDeleteView.as_view(), name="course_delete"),
    
    # Pdf resource
    path("PDF-resource/list/", views.PDFBookResourceListView.as_view(), name="pdf_book_resource_list"),
    path("PDF-resource/<str:pk>/detail/", views.PDFBookResourceDetailView.as_view(), name="pdf_book_resource_detail"),
    path("new/PDF-resource/create/<str:pk>/", views.PDFBookResourceCreateView.as_view(), name="pdfbook_resource_create"),
    path("new/PDF-resource/create/", views.PDFBookResourceCreateView.as_view(), name="pdfbook_resource_create"),
    path("PDF-resource/<str:pk>/update/", views.PDFBookResourceUpdateView.as_view(), name="pdf_book_resource_update"),
    path("PDF-resource/<str:pk>/delete/", views.PDFBookResourceDeleteView.as_view(), name="pdf_book_resource_delete"),
    
    #Pdf List
    path("PDF/list/", views.PDFBookListView.as_view(), name="pdf_book_list"),
    # path("PDF/<str:pk>/detail/", views.PDFBookDetailView.as_view(), name="pdf_book_detail"),
    
    #Syllabus
    path("syllabus/list/", views.SyllabusListView.as_view(), name="syllabus_list"),
    # path("syllabus/<str:pk>/detail/", views.SyllabusDetailView.as_view(), name="syllabus_detail"),
    path('syllabus/<int:course_pk>/<int:batch_pk>/detail/', views.SyllabusDetailView.as_view(), name='syllabus_detail'),
    path('courses/<int:course_id>/syllabus/create/', views.SyllabusCreateView.as_view(), name='syllabus_create'),
    path("new/syllabus/", views.SyllabusCreateView.as_view(), name="syllabus_create"),
    path("syllabus/<str:pk>/update/", views.SyllabusUpdateView.as_view(), name="syllabus_update"),
    path('courses/<int:course_id>/syllabus/update/', views.SyllabusUpdateView.as_view(), name='syllabus_create'),
    path("syllabus/<str:pk>/delete/", views.SyllabusDeleteView.as_view(), name="syllabus_delete"),

    #Complaint
    path("complaint/list/", views.ComplaintListView.as_view(), name="complaint_list"),
    path("complaint/<str:pk>/detail/", views.ComplaintDetailView.as_view(), name="complaint_detail"),
    path("new/complaint/<str:pk>/", views.ComplaintCreateView.as_view(), name="complaint_create"),
    path("new/complaint/", views.ComplaintCreateView.as_view(), name="complaint_create"),
    path("complaint/<str:pk>/update/", views.ComplaintUpdateView.as_view(), name="complaint_update"),
    path("complaint/<str:pk>/delete/", views.ComplaintDeleteView.as_view(), name="complaint_delete"),

    #Update
    path("update/list/", views.UpdateListView.as_view(), name="update_list"),
    path("update/<str:pk>/detail/", views.UpdateDetailView.as_view(), name="update_detail"),
    path("new/update/<str:pk>/", views.UpdateCreateView.as_view(), name="update_create"),
    path("new/update/", views.UpdateCreateView.as_view(), name="update_create"),
    path("update/<str:pk>/update/", views.UpdateUpdateView.as_view(), name="update_update"),
    path("update/<str:pk>/delete/", views.UpdateDeleteView.as_view(), name="update_delete"),

    #Placement Request
    path("placement-requests/list/", views.PlacementRequestListView.as_view(), name="placement_request_list"),
    path("placement-request/<str:pk>/detail/", views.PlacementRequestDetailView.as_view(), name="placement_request_detail"),
    path("new/placement-request/<str:pk>/", views.PlacementRequestCreateView.as_view(), name="placement_request_create"),
    path("new/placement-request/", views.PlacementRequestCreateView.as_view(), name="placement_request_create"),
    path("placement-request/<str:pk>/update/", views.PlacementRequestUpdateView.as_view(), name="placement_request_update"),
    path("placement-request/<str:pk>/delete/", views.PlacementRequestDeleteView.as_view(), name="placement_request_delete"),

    #Chat
    path("chat/list/", views.ChatListView.as_view(), name="chat_list"),
    path("chat/employee/list/", views.EmployeeChatListView.as_view(), name="employee_chat_list"),
    path('chat/student/<int:user_id>/', views.StudentChatView.as_view(), name='student_chat'),
    path('chat/<int:user_id>/clear/', views.clear_chat, name='clear_chat')

]

oxdu_erp/urls.py
from core.mixins import OpenView

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.utils.translation import gettext_lazy as _


module_urls = i18n_patterns(
    path("", include("core.urls", namespace="core")),
    path("", include("user_sessions.urls", "user_sessions")),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("registration.backends.simple.urls")),
    # path("login/", CustomLoginView.as_view(), name="auth_login"),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("employees/", include("employees.urls", namespace="employees")),
    path("admission/", include("admission.urls", namespace="admission")),
    path("branches/", include("branches.urls", namespace="branches")),
    path("masters/", include("masters.urls", namespace="masters")),
    prefix_default_language=False,
)

plugin_urls = [
    path("tinymce/", include("tinymce.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("sitemap.xml", OpenView.as_view(template_name="sitemap.xml", content_type="text/xml")),
    path("robots.txt", OpenView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("OneSignalSDKWorker.js", OpenView.as_view(template_name="OneSignalSDKWorker.js", content_type="text/javascript")),
]

urlpatterns = module_urls + plugin_urls + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

PROJECT_NAME = settings.APP_SETTINGS.get("site_name")
admin.site.site_header = _("%(project_name)s Administration") % {"project_name": PROJECT_NAME}
admin.site.site_title = _("%(project_name)s Admin Portal") % {"project_name": PROJECT_NAME}
admin.site.index_title = _("Welcome to %(project_name)s Admin Portal") % {"project_name": PROJECT_NAME}

employees/forms.py
from core.base import BaseForm

from .models import Department
from .models import Designation
from .models import Employee
from masters.models import Course
from django import forms


class DepartmentForm(BaseForm):
    class Meta:
        model = Department
        fields = "__all__"


class DesignationForm(BaseForm):
    class Meta:
        model = Designation
        fields = "__all__"
        
    
class CourseForm(BaseForm):
    class Meta:
        model = Course
        fields = "__all__"


class EmployeeForm(BaseForm):
    class Meta:
        model = Employee
        exclude = ("user", "status", "resigned_date", "notice_date", "resigned_form", "termination_date", "termination_reason")


class EmployeePhotoForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['photo']
        widgets = {'photo': forms.FileInput(attrs={'class': 'form-control d-none'})}


class EmployeePersonalDataForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = (
            "is_active",
            "first_name",
            "last_name",
            "personal_email",
            "gender",
            "marital_status",
            "mobile",
            "whatsapp",
            "date_of_birth",
            "religion",
            "blood_group",
            "experience",
            "qualifications",
            "photo",
        )

    def __init__(self, *args, **kwargs):
        super(EmployeePersonalDataForm, self).__init__(*args, **kwargs)
        self.fields['experience'].widget.attrs['rows'] = 3
        self.fields['qualifications'].widget.attrs['rows'] = 3


class EmployeeParentDataForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ("is_active", "father_name", "father_mobile", "mother_name", "guardian_name", "guardian_mobile", "relationship_with_employee")


class EmployeeAddressDataForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ("is_active", "type_of_residence", "residence_name", "residential_address", "residence_contact", "residential_zip_code", "permanent_address", "permanent_zip_code")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['residential_address'].widget.attrs['rows'] = 3
        self.fields['permanent_address'].widget.attrs['rows'] = 3


class EmployeeOfficialDataForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = (
            "is_active",
            "branch",
            "employee_id",
            "department",
            "designation",
            "course",
            "is_also_tele_caller",
            "date_of_confirmation",
            "date_of_joining",
            "official_email",
            "employment_type",
            "offer_letter",
            "joining_letter",
            "agreement_letter",
            "experience_letter",
        )


class EmployeeFinancialDataForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ("is_active", "bank_name", "account_name", "bank_branch", "account_number", "ifsc_code", "basic_salary", "hra", "transportation_allowance", "other_allowance")

templates/employees/partials/course_form_modal.html
{% load static crispy_forms_tags %}

<div class="modal fade" id="course-form-modal" tabindex="-1" aria-labelledby="course-form-modalLabel"
    aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog modal-dialog-centered modal-lg ">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="course-form-modalLabel">Course Form</h5>
                <button type="button" class="btn-close btn-sm" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'masters:course_create' %}" class="" id="course-form">
                    {% csrf_token %}
                    {{ course_form|crispy }}
                    <div class="modal-footer mt-4">
                        <button type="button" class="btn btn-outline-grey" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="reset" class="btn btn-secondary">Reset</button>
                    </div>
                </form>

            </div>

        </div>
    </div>
</div>

templates/employees/partials/department_form_modal.html
{% load static crispy_forms_tags %}

<div class="modal fade" id="department-form-modal" tabindex="-1" aria-labelledby="department-form-modalLabel"
    aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog modal-dialog-centered modal-lg ">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="department-form-modalLabel">Department Form</h5>
                <button type="button" class="btn-close btn-sm" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'employees:department_create' %}" class="" id="department-form">
                    {% csrf_token %}
                    {{ department_form|crispy }}
                    <div class="modal-footer mt-4">
                        <button type="button" class="btn btn-outline-grey" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="reset" class="btn btn-secondary">Reset</button>
                    </div>
                </form>

            </div>

        </div>
    </div>
</div>

templates/employees/partials/designation_form_modal.html
{% load static crispy_forms_tags %}

<div class="modal fade" id="designation-form-modal" tabindex="-1" aria-labelledby="designation-form-modalLabel"
    aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog modal-dialog-centered modal-lg ">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="designation-form-modalLabel">Designation Form</h5>
                <button type="button" class="btn-close btn-sm" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'employees:designation_create' %}" class="" id="designation-form">
                    {% csrf_token %}
                    {{ designation_form|crispy }}
                    <div class="modal-footer mt-4">
                        <button type="button" class="btn btn-outline-grey" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="reset" class="btn btn-secondary">Reset</button>
                    </div>
                </form>

            </div>

        </div>
    </div>
</div>